// spotless:off
package frc.robot.auto;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftBasic = new ChoreoTraj(
        "LeftBasic",
        OptionalInt.empty(),
        2.47262,
        new Pose2d(3.60111, 7.37503, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.2503, 7.20585, Rotation2d.fromRadians(3.12983))
    );
    public static final ChoreoTraj LeftTrench = new ChoreoTraj(
        "LeftTrench",
        OptionalInt.empty(),
        10.4236,
        new Pose2d(4.43873, 7.42359, Rotation2d.fromRadians(0)),
        new Pose2d(1.51523, 7.4094, Rotation2d.fromRadians(3.1183))
    );
    public static final ChoreoTraj RightBasic = new ChoreoTraj(
        "RightBasic",
        OptionalInt.empty(),
        3.12472,
        new Pose2d(3.64399, 0.63993, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.63534, 0.68251, Rotation2d.fromRadians(3.12983))
    );
    public static final ChoreoTraj RightBasicNoIntake = new ChoreoTraj(
        "RightBasicNoIntake",
        OptionalInt.empty(),
        3.12472,
        new Pose2d(3.64399, 0.63993, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.63534, 0.68251, Rotation2d.fromRadians(3.12983))
    );
    public static final ChoreoTraj RightTrench = new ChoreoTraj(
        "RightTrench",
        OptionalInt.empty(),
        15.02969,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.42544, 2.41536, Rotation2d.fromRadians(-3.07233))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrench$0 = new ChoreoTraj(
        "RightTrench",
        OptionalInt.of(0),
        8.27165,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.67796, 0.67272, Rotation2d.fromRadians(-3.14057))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrench$1 = new ChoreoTraj(
        "RightTrench",
        OptionalInt.of(1),
        6.758040000000001,
        new Pose2d(2.67796, 0.67272, Rotation2d.fromRadians(-3.14057)),
        new Pose2d(3.42544, 2.41536, Rotation2d.fromRadians(-3.07233))
    );
    public static final ChoreoTraj RightTrenchBump = new ChoreoTraj(
        "RightTrenchBump",
        OptionalInt.empty(),
        14.40787,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(6.10985, 3.43886, Rotation2d.fromRadians(1.62835))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrenchBump$0 = new ChoreoTraj(
        "RightTrenchBump",
        OptionalInt.of(0),
        6.87918,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(3.5729, 2.51745, Rotation2d.fromRadians(-3.13442))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrenchBump$1 = new ChoreoTraj(
        "RightTrenchBump",
        OptionalInt.of(1),
        7.528690000000001,
        new Pose2d(3.5729, 2.51745, Rotation2d.fromRadians(-3.13442)),
        new Pose2d(6.10985, 3.43886, Rotation2d.fromRadians(1.62835))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("LeftBasic", LeftBasic),
        Map.entry("LeftTrench", LeftTrench),
        Map.entry("RightBasic", RightBasic),
        Map.entry("RightBasicNoIntake", RightBasicNoIntake),
        Map.entry("RightTrench", RightTrench),
        Map.entry("RightTrench$0", RightTrench$0),
        Map.entry("RightTrench$1", RightTrench$1),
        Map.entry("RightTrenchBump", RightTrenchBump),
        Map.entry("RightTrenchBump$0", RightTrenchBump$0),
        Map.entry("RightTrenchBump$1", RightTrenchBump$1)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
