// spotless:off
package frc.robot.auto;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftBasic = new ChoreoTraj(
        "LeftBasic",
        OptionalInt.empty(),
        2.47262,
        new Pose2d(3.60111, 7.37503, Rotation2d.fromRadians(3.14159)),
        new Pose2d(1.2503, 7.20585, Rotation2d.fromRadians(3.12983))
    );
    public static final ChoreoTraj LeftTrench = new ChoreoTraj(
        "LeftTrench",
        OptionalInt.empty(),
        10.39963,
        new Pose2d(4.46711, 7.5797, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(1.51523, 7.4094, Rotation2d.fromRadians(3.1183))
    );
    public static final ChoreoTraj LeftTrenchBump = new ChoreoTraj(
        "LeftTrenchBump",
        OptionalInt.empty(),
        11.1981,
        new Pose2d(4.46318, 7.62527, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(1.76419, 6.79831, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftTrenchBump$0 = new ChoreoTraj(
        "LeftTrenchBump",
        OptionalInt.of(0),
        7.89398,
        new Pose2d(4.46318, 7.62527, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.85601, 5.58222, Rotation2d.fromRadians(3.13818))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj LeftTrenchBump$1 = new ChoreoTraj(
        "LeftTrenchBump",
        OptionalInt.of(1),
        3.30412,
        new Pose2d(2.85601, 5.58222, Rotation2d.fromRadians(3.13818)),
        new Pose2d(1.76419, 6.79831, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj RightBasic = new ChoreoTraj(
        "RightBasic",
        OptionalInt.empty(),
        3.12472,
        new Pose2d(3.64399, 0.63993, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.63534, 0.68251, Rotation2d.fromRadians(3.12983))
    );
    public static final ChoreoTraj RightBasicNoIntake = new ChoreoTraj(
        "RightBasicNoIntake",
        OptionalInt.empty(),
        3.12472,
        new Pose2d(3.64399, 0.63993, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.63534, 0.68251, Rotation2d.fromRadians(3.12983))
    );
    public static final ChoreoTraj RightTrench = new ChoreoTraj(
        "RightTrench",
        OptionalInt.empty(),
        9.32505,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(0.66372, 0.71089, Rotation2d.fromRadians(-3.13384))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrench$0 = new ChoreoTraj(
        "RightTrench",
        OptionalInt.of(0),
        8.20603,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.67796, 0.67272, Rotation2d.fromRadians(-3.14101))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrench$1 = new ChoreoTraj(
        "RightTrench",
        OptionalInt.of(1),
        1.119019999999999,
        new Pose2d(2.67796, 0.67272, Rotation2d.fromRadians(-3.14101)),
        new Pose2d(0.66372, 0.71089, Rotation2d.fromRadians(-3.13384))
    );
    public static final ChoreoTraj RightTrenchBump = new ChoreoTraj(
        "RightTrenchBump",
        OptionalInt.empty(),
        12.21264,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(1.62465, 0.98004, Rotation2d.fromRadians(3.14159))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrenchBump$0 = new ChoreoTraj(
        "RightTrenchBump",
        OptionalInt.of(0),
        8.70294,
        new Pose2d(4.46035, 0.44309, Rotation2d.fromRadians(1.5708)),
        new Pose2d(2.16108, 2.62944, Rotation2d.fromRadians(-3.08112))
    );
    /** ERROR: Can only use letters, 0-9, and _. Can't use $. Rename it in the Choreo app to fix this error. */
    public static final ChoreoTraj RightTrenchBump$1 = new ChoreoTraj(
        "RightTrenchBump",
        OptionalInt.of(1),
        3.5097000000000005,
        new Pose2d(2.16108, 2.62944, Rotation2d.fromRadians(-3.08112)),
        new Pose2d(1.62465, 0.98004, Rotation2d.fromRadians(3.14159))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("LeftBasic", LeftBasic),
        Map.entry("LeftTrench", LeftTrench),
        Map.entry("LeftTrenchBump", LeftTrenchBump),
        Map.entry("LeftTrenchBump$0", LeftTrenchBump$0),
        Map.entry("LeftTrenchBump$1", LeftTrenchBump$1),
        Map.entry("RightBasic", RightBasic),
        Map.entry("RightBasicNoIntake", RightBasicNoIntake),
        Map.entry("RightTrench", RightTrench),
        Map.entry("RightTrench$0", RightTrench$0),
        Map.entry("RightTrench$1", RightTrench$1),
        Map.entry("RightTrenchBump", RightTrenchBump),
        Map.entry("RightTrenchBump$0", RightTrenchBump$0),
        Map.entry("RightTrenchBump$1", RightTrenchBump$1)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
